version: 2

references:
  images:
    go: &GOLANG_IMAGE golang:1.12.5-stretch  # Pin Go to patch version (ex: 1.2.3)

  environment: &ENVIRONMENT
    GO_VERSION: 1.12.5  # Pin Go to patch version (ex: 1.2.3)
    GOTESTSUM_VERSION: 0.3.3  # Pin gotestsum to patch version (ex: 1.2.3)

jobs:
  build:
    docker:
      - image: *GOLANG_IMAGE
    environment:
      <<: *ENVIRONMENT
    steps:
      - checkout
      - run:
          name: Build library
          command: go build $(go list ./... | grep -v /vendor/ | grep -v tests )

  test:
    docker:
      - image: *GOLANG_IMAGE
    environment:
      <<: *ENVIRONMENT
    steps:
      - checkout
      - run:
          name: Run Go tests
          command: |
            set -eux -o pipefail

            # Install gotestsum
            curl -sSL "https://github.com/gotestyourself/gotestsum/releases/download/v${GOTESTSUM_VERSION}/gotestsum_${GOTESTSUM_VERSION}_linux_amd64.tar.gz" | tar --overwrite -xz gotestsum

            # Run tests
            mkdir test-reports
            CGO_ENABLED=0 \
              ./gotestsum --format=short-verbose --junitfile test-reports/results.xml -- \
                -timeout=10m \
                -parallel=20 \
                $(go list ./... | grep -v /vendor/ )
      - store_test_results:
          path: test-reports

workflows:
  version: 2

  ci:
    jobs:
      - build
      - test:
          requires:
            - build
